{ id: '234488146',
  username: 'stevetyler_uk',
  displayName: 'Steve Tyler',
  photos: [ { value: 'https://pbs.twimg.com/profile_images/378800000309188708/e405cd674ae329dc8dfb15e92e0a8d1e_normal.jpeg' } ],
  provider: 'twitter',
  _raw: '{"id":234488146,"id_str":"234488146","name":"Steve Tyler","screen_name":"stevetyler_uk","location":"Stratford, London","profile_location":null,"description":"IT Support Consultant & Web Developer","url":"http:\\/\\/t.co\\/z80ouFqXEw","entities":{"url":{"urls":[{"url":"http:\\/\\/t.co\\/z80ouFqXEw","expanded_url":"http:\\/\\/steve-tyler.co.uk","display_url":"steve-tyler.co.uk","indices":[0,22]}]},"description":{"urls":[]}},"protected":false,"followers_count":98,"friends_count":277,"listed_count":8,"created_at":"Wed Jan 05 19:49:46 +0000 2011","favourites_count":1360,"utc_offset":0,"time_zone":"London","geo_enabled":false,"verified":false,"statuses_count":66,"lang":"en","status":{"created_at":"Mon Mar 16 14:20:26 +0000 2015","id":577474510460493824,"id_str":"577474510460493824","text":"The argument for divesting from fossil fuels is becoming an overwhelming one | Alan Rusbridger http:\\/\\/t.co\\/PkE1NxvtfV","source":"\\u003ca href=\\"http:\\/\\/twitter.com\\" rel=\\"nofollow\\"\\u003eTwitter Web Client\\u003c\\/a\\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"geo":null,"coordinates":null,"place":null,"contributors":null,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"symbols":[],"user_mentions":[],"urls":[{"url":"http:\\/\\/t.co\\/PkE1NxvtfV","expanded_url":"http:\\/\\/gu.com\\/p\\/46jp8\\/stw","display_url":"gu.com\\/p\\/46jp8\\/stw","indices":[95,117]}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"lang":"en"},"contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png","profile_background_image_url_https":"https:\\/\\/abs.twimg.com\\/images\\/themes\\/theme1\\/bg.png","profile_background_tile":false,"profile_image_url":"http:\\/\\/pbs.twimg.com\\/profile_images\\/378800000309188708\\/e405cd674ae329dc8dfb15e92e0a8d1e_normal.jpeg","profile_image_url_https":"https:\\/\\/pbs.twimg.com\\/profile_images\\/378800000309188708\\/e405cd674ae329dc8dfb15e92e0a8d1e_normal.jpeg","profile_link_color":"0084B4","profile_sidebar_border_color":"000000","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":false,"default_profile":false,"default_profile_image":false,"following":false,"follow_request_sent":false,"notifications":false,"suspended":false,"needs_phone_verification":false}',
  // parsed by Passport
  _json: 
   { id: 234488146,
     id_str: '234488146',
     name: 'Steve Tyler',
     screen_name: 'stevetyler_uk',
     location: 'Stratford, London',
     profile_location: null,
     description: 'IT Support Consultant & Web Developer',
     url: 'http://t.co/z80ouFqXEw',
     entities: 
      { url: 
         { urls: 
            [ { url: 'http://t.co/z80ouFqXEw',
                expanded_url: 'http://steve-tyler.co.uk',
                display_url: 'steve-tyler.co.uk',
                indices: [ 0, 22 ] } ] },
        description: { urls: [] } },
     protected: false,
     followers_count: 98,
     friends_count: 277,
     listed_count: 8,
     created_at: 'Wed Jan 05 19:49:46 +0000 2011',
     favourites_count: 1360,
     utc_offset: 0,
     time_zone: 'London',
     geo_enabled: false,
     verified: false,
     statuses_count: 66,
     lang: 'en',
     status: 
      { created_at: 'Mon Mar 16 14:20:26 +0000 2015',
        id: 577474510460493800,
        id_str: '577474510460493824',
        text: 'The argument for divesting from fossil fuels is becoming an overwhelming one | Alan Rusbridger http://t.co/PkE1NxvtfV',
        source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweet_count: 0,
        favorite_count: 0,
        entities: 
         { hashtags: [],
           symbols: [],
           user_mentions: [],
           urls: 
            [ { url: 'http://t.co/PkE1NxvtfV',
                expanded_url: 'http://gu.com/p/46jp8/stw',
                display_url: 'gu.com/p/46jp8/stw',
                indices: [ 95, 117 ] } ] },
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://pbs.twimg.com/profile_images/378800000309188708/e405cd674ae329dc8dfb15e92e0a8d1e_normal.jpeg',
     profile_image_url_https: 'https://pbs.twimg.com/profile_images/378800000309188708/e405cd674ae329dc8dfb15e92e0a8d1e_normal.jpeg',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: '000000',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: false,
     default_profile: false,
     default_profile_image: false,
     following: false,
     follow_request_sent: false,
     notifications: false,
     suspended: false,
     needs_phone_verification: false },
  _accessLevel: 'read' }